# Netlify configuration for Nationwide Equities Reverse Mortgage Calculator

[build]
  command = "npm run build"
  publish = "dist/public"
  functions = "netlify/functions"

# Exclude SEO files from SPA routing
[[redirects]]
  from = "/robots.txt"
  to = "/robots.txt"
  status = 200

[[redirects]]
  from = "/sitemap.xml"
  to = "/sitemap.xml"
  status = 200

# SPA routing - redirect all requests to index.html
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Security headers
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "no-referrer-when-downgrade"
    Permissions-Policy = "geolocation=(), camera=(), microphone=()"
    Strict-Transport-Security = "max-age=63072000; includeSubDomains; preload"
    X-XSS-Protection = "1; mode=block"

# Cache headers for static assets
[[headers]]
  for = "/assets/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/*.js"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/*.css"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

# Environment variables to set in Netlify UI:
# 
# Lead Notification Email:
# - In Netlify Dashboard > Site settings > Functions > Environment variables
# - Add: NOTIFICATION_EMAIL = Salesmanager@nwecorp.com
# - Or use WEBHOOK_URL for CRM integration (Zapier, Make, Google Sheets, etc.)
#
# Brand Configuration:
# - VITE_PHONE_CTA - Phone number link (e.g., tel:+1-866-312-4370)
# - VITE_PHONE_DISPLAY - Phone number display (e.g., 866-312-4370)
# - VITE_NMLS_ID - NMLS license number (e.g., 1408)
# - VITE_BRAND_NAME - Company name (e.g., Nationwide Equities)
